# List of the feature types supported by the vision server.
uint32 FEATURE_BOOL = 0
uint32 FEATURE_INT = 1
uint32 FEATURE_DOUBLE = 2

string camera_name
string camera_feature

---

string feature_value
uint32 feature_type
