echo "-----BOTTOM------"
echo "RED"
rosservice call /provider_vision/get_media_param_list "bottom" "WHITE_BALANCE_RED"
echo "BLUE"
rosservice call /provider_vision/get_media_param_list "bottom" "WHITE_BALANCE_BLUE"
echo "SHUTTER"
rosservice call /provider_vision/get_media_param_list "bottom" "SHUTTER"
echo
echo "-----FRONT-----"
echo "RED"
rosservice call /provider_vision/get_media_param_list "front_guppy" "WHITE_BALANCE_RED"
echo "BLUE"
rosservice call /provider_vision/get_media_param_list "front_guppy" "WHITE_BALANCE_BLUE"
echo "SHUTTER"
rosservice call /provider_vision/get_media_param_list "front_guppy" "SHUTTER"
